// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEFmPlF4vIrtJ901tA0SxfWVzkiyQDxI',
    appId: '1:12414139549:web:255d0a1e8e4063c9fda874',
    messagingSenderId: '12414139549',
    projectId: 'hackaton-4f772',
    authDomain: 'hackaton-4f772.firebaseapp.com',
    storageBucket: 'hackaton-4f772.appspot.com',
    measurementId: 'G-TCZZQXYEB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAGFN_nxEdcUdNkLLIdYxEmUROP7zVzU0',
    appId: '1:12414139549:android:fcc3dfaba6e25506fda874',
    messagingSenderId: '12414139549',
    projectId: 'hackaton-4f772',
    storageBucket: 'hackaton-4f772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_brs4dv-rp1C3c16Sse3t_0brvKP1vLw',
    appId: '1:12414139549:ios:cc13d180ccb58784fda874',
    messagingSenderId: '12414139549',
    projectId: 'hackaton-4f772',
    storageBucket: 'hackaton-4f772.appspot.com',
    iosBundleId: 'com.example.hackaton2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_brs4dv-rp1C3c16Sse3t_0brvKP1vLw',
    appId: '1:12414139549:ios:9f4baa144bec844dfda874',
    messagingSenderId: '12414139549',
    projectId: 'hackaton-4f772',
    storageBucket: 'hackaton-4f772.appspot.com',
    iosBundleId: 'com.example.hackaton2.RunnerTests',
  );
}
